# CodeRabbit Configuration
# Enforces .cursorrules standards and enterprise-grade quality gates

# Language and framework settings
language: typescript
framework: react

# Review settings
reviews:
  # Enable comprehensive reviews
  auto_review: true
  
  # Focus areas aligned with .cursorrules
  focus_areas:
    - code_quality
    - security
    - performance
    - maintainability
    - typescript_best_practices
    - react_patterns

# File size limits (aligned with .cursorrules)
limits:
  file_lines: 500
  function_lines: 40
  component_lines: 200
  hook_lines: 100
  service_lines: 200

# Code quality rules
rules:
  # Enforce single responsibility principle
  single_responsibility: true
  
  # Naming conventions
  naming:
    components: PascalCase
    functions: camelCase
    variables: camelCase
    
  # Architecture patterns
  architecture:
    enforce_separation_of_concerns: true
    require_manager_service_pattern: true
    enforce_modular_design: true

# Security scanning
security:
  vulnerability_detection: true
  dependency_scanning: true
  code_pattern_analysis: true

# Performance monitoring
performance:
  bundle_size_analysis: true
  render_optimization: true
  memory_leak_detection: true

# TypeScript strictness
typescript:
  strict_mode: true
  no_any: warn
  explicit_return_types: true

# Ignore patterns
ignore:
  # Generated files
  - "**/*.generated.*"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  
  # Configuration files
  - "**/*.config.*"
  - "**/.*rc.*"
  
  # Test files (for now)
  - "**/*.test.*"
  - "**/*.spec.*"

# Custom patterns to enforce
patterns:
  # Enforce file organization
  - pattern: "UI components should be in src/components/"
    files: "src/components/**/*.tsx"
    
  - pattern: "Business logic should be in src/services/"
    files: "src/services/**/*.ts"
    
  - pattern: "Custom hooks should be in src/hooks/"
    files: "src/hooks/**/*.ts"
    
  - pattern: "Context providers should be in src/providers/"
    files: "src/providers/**/*.tsx"

# Integration settings
integration:
  github:
    auto_comment: true
    require_approval: false
    dismiss_stale_reviews: true
