# CodeRabbit Configuration for StatJam
# Simplified version to fix parsing errors

# Review settings
reviews:
  auto_review: true
  
# Files to ignore
ignore:
  - "*.md"
  - "*.json"
  - "package-lock.json"
  - "node_modules/**"
  - ".next/**"
  - "dist/**"
  - "build/**"
  - "archive/**"
  - "docs/08-archive/**"
  - "**/*.test.{ts,tsx,js,jsx}"
  - "**/*.spec.{ts,tsx,js,jsx}"
  - "**/tests/**"
  - "tailwind.config.ts"
  - "next.config.ts"
  - "eslint.config.mjs"
  - "tsconfig.json"

# GitHub integration
github:
  pr_comments: true
  inline_comments: true
  summary_comments: true

# Language settings
language: en-US

# Review focus areas
focus:
  - security
  - performance
  - best_practices
  - maintainability
  - typescript_issues
  - react_patterns