-- Migration: Create player_cards table for storing generated NBA cards
-- This table stores the cards that players generate using admin-created templates

-- Create player_cards table
CREATE TABLE IF NOT EXISTS player_cards (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    template_variant_id UUID NOT NULL REFERENCES template_variants(id) ON DELETE CASCADE,
    
    -- Store the player data and customizations used to generate the card
    card_data JSONB NOT NULL DEFAULT '{}',
    
    -- URL to the generated card image (stored in Supabase Storage)
    generated_image_url TEXT,
    
    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_player_cards_user_id ON player_cards(user_id);
CREATE INDEX IF NOT EXISTS idx_player_cards_template_variant_id ON player_cards(template_variant_id);
CREATE INDEX IF NOT EXISTS idx_player_cards_created_at ON player_cards(created_at DESC);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_player_cards_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_player_cards_updated_at
    BEFORE UPDATE ON player_cards
    FOR EACH ROW
    EXECUTE FUNCTION update_player_cards_updated_at();

-- Add RLS (Row Level Security) policies
ALTER TABLE player_cards ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only see their own cards
CREATE POLICY "Users can view their own cards" ON player_cards
    FOR SELECT USING (auth.uid() = user_id);

-- Policy: Users can only insert their own cards
CREATE POLICY "Users can insert their own cards" ON player_cards
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Policy: Users can only update their own cards
CREATE POLICY "Users can update their own cards" ON player_cards
    FOR UPDATE USING (auth.uid() = user_id);

-- Policy: Users can only delete their own cards
CREATE POLICY "Users can delete their own cards" ON player_cards
    FOR DELETE USING (auth.uid() = user_id);

-- Policy: Admins can view all cards (for moderation purposes)
CREATE POLICY "Admins can view all cards" ON player_cards
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM users 
            WHERE users.id = auth.uid() 
            AND users.role = 'admin'
        )
    );

-- Add comment for documentation
COMMENT ON TABLE player_cards IS 'Stores NBA cards generated by players using admin-created templates';
COMMENT ON COLUMN player_cards.card_data IS 'JSON object containing player data and customizations used for generation';
COMMENT ON COLUMN player_cards.generated_image_url IS 'URL to the final generated card image in Supabase Storage';
